version: '3.8'

services:
  astra:
    build: .
    container_name: astra
    ports:
      - "8094:8094"
    depends_on:
      - mongo
      - redis
    networks:
      - astra-net
    environment:
      - FLASK_ENV=development
    command: bash -c "flask run --host=0.0.0.0 --port=8094"

  celery:
    build: .
    container_name: astra-celery
    depends_on:
      - redis
      - mongo
    networks:
      - astra-net
    command: celery -A astra.celery_app.celery_app worker --loglevel=info

  mongo:
    image: mongo
    container_name: astra-mongo1
    networks:
      - astra-net

  redis:
    image: redis
    container_name: astra-redis
    networks:
      - astra-net

  vampi:
    image: erev0s/vampi
    container_name: vampi
    ports:
      - "5000:5000"
    environment:
      - vulnerable=1
    networks:
      - astra-net

networks:
  astra-net:
    driver: bridge
